// Canonical source for n8n workflow: GRP - Outreach Drafter (Daily)
// Workflow ID: kgXMHPgseTchGz4o
// Active version verified: 1c659867-8f57-49cc-895b-3a50988fa2b1 (2026-04-26)
//
// Reads top 10 status=new prospects from Prospect-Pipeline (sorted by fit_score desc),
// scrapes each website, drafts personalized cold email via gpt-4o using brand-voice
// + outreach-templates context loaded from Drive, saves draft .txt to Outreach folder,
// marks status=drafted in the sheet. Logs run summary to Drafter-Log.
//
// To deploy:
//   1. update_workflow(workflowId='kgXMHPgseTchGz4o', code=<this file>)
//   2. get_workflow_details — copy the resulting versionId (the draft)
//   3. publish_workflow(workflowId='kgXMHPgseTchGz4o', versionId=<that versionId>)
//
// ⛔ Never edit and Save this workflow from the n8n UI — it overwrites this version.
//    See Marketing/RUNBOOK.md for the hard rule and recovery procedure.

import { workflow, node, trigger, ifElse, splitInBatches, nextBatch, newCredential, expr } from '@n8n/workflow-sdk';

const PROSPECT_PIPELINE_ID = '1sOtDT4OXPu2pVcmLepDyippa0vMXezr9EIsXMcP8iP0';
const PROSPECT_PIPELINE_TAB = 'Prospect-Pipeline';
const DRAFTER_LOG_ID = '1F-m3p1BbgFjTmWpwad8wqlFt6LDyM9X53MR06Uc-90w';
const DRAFTER_LOG_TAB = 'Drafter-Log';
const OUTREACH_FOLDER_ID = '1SB11BM-q5VAVJtlohxr8eCzGFwvUP_Xu';
const BRAND_VOICE_FILE_ID = '10YMhbTYBSbJp5hqyh3FBok7u4cZ4bFHf';
const OUTREACH_TEMPLATES_FILE_ID = '1YYh8G00Zxroya7ybs2utBfhh-zjNi9ve';

const trig = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Daily 9AM IST', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '0 30 3 * * *' }] } }, position: [240, 300] }, output: [{ 'Day of week': 'Monday', timestamp: '2026-04-27T03:30:00.000Z' }] });
const dayRouter = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Day Router', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "const dayMap = { Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 };\nconst item = $input.first();\nconst dowStr = (item && item.json) ? item.json['Day of week'] : null;\nlet day;\nif (dowStr && dayMap[dowStr] !== undefined) { day = dayMap[dowStr]; } else { const now = new Date(); const ist = new Date(now.getTime() + (5.5 * 60 * 60 * 1000)); day = ist.getUTCDay(); }\nconst is_sunday = day === 0;\nconst nowDate = new Date();\nconst istDate = new Date(nowDate.getTime() + (5.5 * 60 * 60 * 1000));\nreturn [{ json: { day: day, is_sunday: is_sunday, run_date: istDate.toISOString().slice(0, 10) } }];" }, position: [440, 300] }, output: [{ day: 1, is_sunday: false, run_date: '2026-04-27' }] });
const skipIf = ifElse({ version: 2.3, config: { name: 'Skip Sunday?', parameters: { conditions: { combinator: 'and', options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 }, conditions: [{ leftValue: expr('{{ $json.is_sunday }}'), rightValue: true, operator: { type: 'boolean', operation: 'true' } }] } }, position: [640, 300] } });
const shapeSkipRow = node({ type: 'n8n-nodes-base.set', version: 3.4, config: { name: 'Shape Skip Row', parameters: { mode: 'manual', assignments: { assignments: [{ id: 's1', name: 'date', value: expr('{{ $now.toISO() }}'), type: 'string' }, { id: 's2', name: 'prospects_processed', value: '0', type: 'string' }, { id: 's3', name: 'drafts_created', value: '0', type: 'string' }, { id: 's4', name: 'drafts_failed', value: '0', type: 'string' }, { id: 's5', name: 'openai_cost_usd', value: '0', type: 'string' }, { id: 's6', name: 'errors', value: '', type: 'string' }, { id: 's7', name: 'status', value: 'skipped_sunday', type: 'string' }] }, includeOtherFields: false }, position: [840, 100] }, output: [{ date: '2026-04-26T03:30:00Z', status: 'skipped_sunday' }] });
const logSkipped = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Log Skipped Run', parameters: { resource: 'sheet', operation: 'append', documentId: { __rl: true, mode: 'id', value: DRAFTER_LOG_ID }, sheetName: { __rl: true, mode: 'name', value: DRAFTER_LOG_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { useAppend: true, handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [1040, 100] }, output: [{ ok: true }] });
const readBrand = node({ type: 'n8n-nodes-base.googleDrive', version: 3, config: { name: 'Read Brand Voice', parameters: { resource: 'file', operation: 'download', fileId: { __rl: true, mode: 'id', value: BRAND_VOICE_FILE_ID }, options: { binaryPropertyName: 'data' } }, credentials: { googleDriveOAuth2Api: newCredential('Google Drive') }, alwaysOutputData: true, executeOnce: true, position: [840, 350] }, output: [{ id: BRAND_VOICE_FILE_ID, name: 'brand-voice.md' }] });
const readTemplates = node({ type: 'n8n-nodes-base.googleDrive', version: 3, config: { name: 'Read Outreach Templates', parameters: { resource: 'file', operation: 'download', fileId: { __rl: true, mode: 'id', value: OUTREACH_TEMPLATES_FILE_ID }, options: { binaryPropertyName: 'data' } }, credentials: { googleDriveOAuth2Api: newCredential('Google Drive') }, alwaysOutputData: true, executeOnce: true, position: [1040, 350] }, output: [{ id: OUTREACH_TEMPLATES_FILE_ID, name: 'outreach-templates.md' }] });
const loadContext = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Load Context', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "function decodeBin(nodeName){ try { const item = $(nodeName).first(); const bin = item && item.binary && item.binary.data; if (bin && bin.data) { return Buffer.from(bin.data, 'base64').toString('utf8'); } } catch(e) {} return ''; }\nconst brand_voice = decodeBin('Read Brand Voice');\nconst templates = decodeBin('Read Outreach Templates');\nreturn [{ json: { brand_voice: brand_voice || '(brand voice file empty)', templates: templates || '(templates file empty)' } }];" }, position: [1240, 350] }, output: [{ brand_voice: '# Brand Voice\n...', templates: '# Templates\n...' }] });
const readPipeline = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Read Prospect Pipeline', parameters: { resource: 'sheet', operation: 'read', documentId: { __rl: true, mode: 'id', value: PROSPECT_PIPELINE_ID }, sheetName: { __rl: true, mode: 'name', value: PROSPECT_PIPELINE_TAB }, options: { returnAllMatches: 'returnAllMatches', dataLocationOnSheet: { values: { rangeDefinition: 'detectAutomatically', readRowsUntil: 'lastRowInSheet' } } } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, alwaysOutputData: true, executeOnce: true, position: [1440, 350] }, output: [{ company: 'Acme', website: 'https://acme.com', status: 'new', fit_score: '8' }] });
const filterSort = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Filter & Sort Prospects', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "const all = $input.all();\nconst news = [];\nfor (const it of all) {\n  const j = (it && it.json) ? it.json : {};\n  const status = String(j.status || '').toLowerCase().trim();\n  if (status !== 'new') continue;\n  if (!j.company || !j.website) continue;\n  const fs = parseInt(j.fit_score, 10);\n  news.push({ ...j, _fit: isNaN(fs) ? 0 : fs });\n}\nnews.sort((a, b) => b._fit - a._fit);\nconst top = news.slice(0, 10);\nif (top.length === 0) return [{ json: { _no_new: true, _candidates: news.length } }];\nreturn top.map(p => { const { _fit, ...rest } = p; return { json: rest }; });" }, position: [1640, 350] }, output: [{ company: 'Acme', website: 'https://acme.com', status: 'new', fit_score: '8', founder_name: 'Jane Doe', email: 'jane@acme.com', country: 'New York, NY', services: 'PPC', signal_notes: 'good fit' }] });
const noNewIf = ifElse({ version: 2.3, config: { name: 'No New Prospects?', parameters: { conditions: { combinator: 'and', options: { caseSensitive: true, leftValue: '', typeValidation: 'loose', version: 2 }, conditions: [{ leftValue: expr('{{ $json._no_new }}'), rightValue: true, operator: { type: 'boolean', operation: 'true' } }] }, looseTypeValidation: true }, position: [1840, 350] } });
const loop = splitInBatches({ version: 3, config: { name: 'Loop Prospects', parameters: { batchSize: 1 }, position: [2040, 350] } });
const scrapeWeb = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Scrape Website', parameters: { method: 'GET', url: expr('{{ $json.website }}'), sendHeaders: true, specifyHeaders: 'keypair', headerParameters: { parameters: [{ name: 'User-Agent', value: 'Mozilla/5.0 (compatible; GoReportPilot-OutreachDrafter/1.0)' }, { name: 'Accept', value: 'text/html,application/xhtml+xml' }] }, options: { response: { response: { responseFormat: 'text', neverError: true } }, timeout: 20000, redirect: { redirect: { followRedirects: true, maxRedirects: 5 } } } }, alwaysOutputData: true, position: [2240, 350] }, output: [{ data: '<html><h1>Acme</h1><h2>Services</h2><ul><li>PPC</li></ul></html>' }] });
const extractCtx = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Extract Website Context', parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const meta = $('Loop Prospects').item.json;\nconst raw = $input.item.json && $input.item.json.data ? String($input.item.json.data) : '';\nlet stripped = raw.replace(/<script[\\s\\S]*?<\\/script>/gi, ' ').replace(/<style[\\s\\S]*?<\\/style>/gi, ' ').replace(/<noscript[\\s\\S]*?<\\/noscript>/gi, ' ').replace(/<!--[\\s\\S]*?-->/g, ' ');\nfunction headings(html, tag){ const out = []; const re = new RegExp('<' + tag + '[^>]*>([\\\\s\\\\S]*?)</' + tag + '>', 'gi'); let m; while ((m = re.exec(html)) !== null && out.length < 30) { const t = m[1].replace(/<[^>]+>/g, ' ').replace(/\\s+/g, ' ').trim(); if (t && t.length > 1 && t.length < 200) out.push(t); } return out; }\nconst h1s = headings(stripped, 'h1');\nconst h2s = headings(stripped, 'h2');\nconst h3s = headings(stripped, 'h3');\nconst imgAlts = []; const altRe = /<img[^>]+alt=\"([^\"]+)\"/gi; let am; while ((am = altRe.exec(stripped)) !== null && imgAlts.length < 30) { const t = am[1].trim(); if (t && t.length > 2 && t.length < 80) imgAlts.push(t); }\nlet text = stripped.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/gi, ' ').replace(/&amp;/gi, '&').replace(/&lt;/gi, '<').replace(/&gt;/gi, '>').replace(/&quot;/gi, '\"').replace(/&#39;/gi, \"'\").replace(/\\s+/g, ' ').trim();\nif (text.length > 4000) text = text.slice(0, 4000);\nconst scrape_failed = !raw || raw.length < 500;\nconst extracted_services = (h2s.concat(h3s)).filter(t => /service|offer|capabilit|solution|expertise|what we do/i.test(t)).slice(0, 5).join(' | ') || h2s.slice(0, 3).join(' | ');\nconst extracted_clients = imgAlts.filter(t => /logo|client/i.test(t)).slice(0, 8).join(' | ');\nconst extracted_blog = h2s.concat(h3s).filter(t => /blog|case study|case stud|insight|article|post/i.test(t)).slice(0, 5).join(' | ');\nreturn { ...meta, _scrape_failed: scrape_failed, scraped_services: extracted_services, scraped_clients: extracted_clients, scraped_blog: extracted_blog, scraped_h1: h1s.slice(0, 3).join(' | '), website_excerpt: text };" }, position: [2440, 350] }, output: [{ company: 'Acme', founder_name: 'Jane', email: 'jane@acme.com', website: 'https://acme.com', country: 'NY', services: 'PPC', fit_score: '8', signal_notes: 'good', scraped_services: 'Paid Search | Meta Ads', scraped_clients: 'ClientCo Logo', scraped_blog: 'How we scaled X', scraped_h1: 'Acme Digital', website_excerpt: 'we run paid social for ecommerce brands', _scrape_failed: false }] });
const draftEmail = node({ type: '@n8n/n8n-nodes-langchain.openAi', version: 2.1, config: { name: 'Draft Email', parameters: { resource: 'text', operation: 'response', modelId: { __rl: true, mode: 'id', value: 'gpt-4o' }, responses: { values: [{ type: 'text', role: 'system', content: "You write cold outreach emails for GoReportPilot, a B2B SaaS reporting tool for digital marketing agencies (GA4 + Meta Ads + Google Ads + Search Console -> narrated PPTX/PDF reports). Follow the brand voice and template structure provided. Reference ONE specific thing from the prospect's website (a service they offer, a client they show, a headline, or a blog post title). Keep body 80-120 words. Subject max 6 words, no spam triggers. Output ONLY a JSON object with keys: subject (string), body (string with newlines as \\n), personalization_hook (string, 1 sentence describing the specific thing you referenced). The body must end with a sign-off line: \\n\\n— Saurabh" }, { type: 'text', role: 'user', content: expr('BRAND VOICE GUIDE:\n{{ $(\"Load Context\").first().json.brand_voice }}\n\n---\n\nTEMPLATE STRUCTURE:\n{{ $(\"Load Context\").first().json.templates }}\n\n---\n\nPROSPECT DATA:\n- Company: {{ $json.company }}\n- Founder: {{ $json.founder_name || \"(unknown)\" }}\n- Email: {{ $json.email }}\n- Website: {{ $json.website }}\n- Country: {{ $json.country }}\n- Services on file: {{ $json.services }}\n- Fit score: {{ $json.fit_score }}/10\n- Signal notes: {{ $json.signal_notes }}\n\nWEBSITE SCRAPE:\n- Scrape succeeded: {{ $json._scrape_failed ? \"NO — work only with Prospect Data above\" : \"YES\" }}\n- H1: {{ $json.scraped_h1 }}\n- Services found: {{ $json.scraped_services }}\n- Client logos found: {{ $json.scraped_clients }}\n- Blog/case study titles: {{ $json.scraped_blog }}\n- Homepage excerpt: {{ ($json.website_excerpt || \"\").slice(0, 1500) }}\n\nDraft the email now. Output JSON only.') }] }, simplify: true, options: { maxTokens: 700, temperature: 0.4, textFormat: { textOptions: [{ type: 'json_object' }] } } }, credentials: { openAiApi: newCredential('OpenAI') }, position: [2640, 350] }, output: [{ content: '{"subject": "your case study on retailco", "body": "Saw your case study on RetailCo...", "personalization_hook": "Referenced their RetailCo case study"}' }] });
const parseDraft = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Parse Draft', parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const j = $input.item.json || {};\nlet raw = '';\nif (typeof j === 'string') raw = j;\nelse if (typeof j.content === 'string') raw = j.content;\nelse if (typeof j.text === 'string') raw = j.text;\nelse if (typeof j.output_text === 'string') raw = j.output_text;\nelse if (typeof j.output === 'string') raw = j.output;\nelse if (j.message && typeof j.message.content === 'string') raw = j.message.content;\nelse if (Array.isArray(j.output)) {\n  for (const o of j.output) { const cs = Array.isArray(o.content) ? o.content : (o.content ? [o.content] : []); for (const c of cs) { if (c && typeof c.text === 'string') raw += c.text; } }\n}\nif (!raw) raw = JSON.stringify(j);\nlet parsed = null;\ntry { parsed = JSON.parse(raw); } catch(e) { const m = raw.match(/\\{[\\s\\S]*\\}/); if (m) { try { parsed = JSON.parse(m[0]); } catch(_) {} } }\nif (!parsed || typeof parsed !== 'object') parsed = { subject: 'parse_failed', body: raw.slice(0, 800), personalization_hook: '' };\nconst meta = $('Extract Website Context').item.json;\nreturn { ...meta, draft_subject: String(parsed.subject || '').slice(0, 200), draft_body: String(parsed.body || ''), draft_hook: String(parsed.personalization_hook || '').slice(0, 300), _draft_ok: !!(parsed.subject && parsed.body) };" }, position: [2840, 350] }, output: [{ company: 'Acme', founder_name: 'Jane', email: 'jane@acme.com', website: 'https://acme.com', fit_score: '8', _scrape_failed: false, draft_subject: 'your retailco case study', draft_body: 'Saw your case study...', draft_hook: 'Referenced RetailCo', _draft_ok: true }] });
const shapeDraftDoc = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Shape Draft Doc', parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const j = $input.item.json;\nconst date = new Date();\nconst ist = new Date(date.getTime() + (5.5 * 60 * 60 * 1000));\nconst d = ist.toISOString().slice(0, 10);\nconst slug = String(j.company || 'unknown').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);\nconst doc_name = d + '-' + slug + '.txt';\nconst content = 'Subject: ' + (j.draft_subject || '') + '\\n\\nTo: ' + (j.founder_name || '(unknown)') + ' (' + (j.email || '') + ')\\nCompany: ' + (j.company || '') + '\\nWebsite: ' + (j.website || '') + '\\nFit score: ' + (j.fit_score || '') + '/10\\n\\n---\\n\\n' + (j.draft_body || '') + '\\n\\n---\\n\\nPersonalization hook: ' + (j.draft_hook || '(none)') + '\\nScrape succeeded: ' + (j._scrape_failed ? 'NO' : 'YES') + '\\nGenerated at: ' + new Date().toISOString();\nreturn { ...j, doc_name: doc_name, doc_content: content };" }, position: [3040, 350] }, output: [{ company: 'Acme', website: 'https://acme.com', doc_name: '2026-04-26-acme.txt', doc_content: 'Subject: ...\n\nTo: Jane (jane@acme.com)\n...' }] });
const saveDraft = node({ type: 'n8n-nodes-base.googleDrive', version: 3, config: { name: 'Save Draft to Drive', parameters: { resource: 'file', operation: 'createFromText', content: expr('{{ $json.doc_content }}'), name: expr('{{ $json.doc_name }}'), driveId: { __rl: true, mode: 'list', value: 'My Drive' }, folderId: { __rl: true, mode: 'id', value: OUTREACH_FOLDER_ID }, options: { convertToGoogleDocument: false } }, credentials: { googleDriveOAuth2Api: newCredential('Google Drive') }, alwaysOutputData: true, position: [3240, 350] }, output: [{ id: 'newfileid', name: '2026-04-26-acme.txt', webViewLink: 'https://drive.google.com/file/d/newfileid/view' }] });
const shapeStatusUpdate = node({ type: 'n8n-nodes-base.set', version: 3.4, config: { name: 'Shape Status Update', parameters: { mode: 'manual', assignments: { assignments: [{ id: 'su1', name: 'website', value: expr("{{ $('Shape Draft Doc').item.json.website }}"), type: 'string' }, { id: 'su2', name: 'status', value: 'drafted', type: 'string' }] }, includeOtherFields: false }, position: [3440, 350] }, output: [{ website: 'https://acme.com', status: 'drafted' }] });
const updateStatus = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Update Status to Drafted', parameters: { resource: 'sheet', operation: 'appendOrUpdate', documentId: { __rl: true, mode: 'id', value: PROSPECT_PIPELINE_ID }, sheetName: { __rl: true, mode: 'name', value: PROSPECT_PIPELINE_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: ['website'], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [3640, 350] }, output: [{ ok: true }] });
const shapeRunLog = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Shape Run Log Row', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "function safeAll(name){ try { return $(name).all() || []; } catch(e){ return []; } }\nfunction safeFirstJson(name){ try { return $(name).first().json || {}; } catch(e){ return {}; } }\nconst filterMeta = safeFirstJson('Filter & Sort Prospects');\nconst isNoNew = !!filterMeta._no_new;\nconst filterAll = safeAll('Filter & Sort Prospects');\nconst processed = isNoNew ? 0 : filterAll.filter(it => it && it.json && !it.json._no_new).length;\nconst created = processed;\nconst failed = 0;\nconst cost = (processed * 0.05).toFixed(4);\nlet status = 'success';\nif (isNoNew) status = 'no_new_prospects';\nelse if (processed === 0) status = 'no_new_prospects';\nreturn [{ json: {\n  date: new Date().toISOString(),\n  prospects_processed: String(processed),\n  drafts_created: String(created),\n  drafts_failed: String(failed),\n  openai_cost_usd: cost,\n  errors: '',\n  status: status\n} }];" }, position: [2240, 700] }, output: [{ date: '2026-04-26T03:30:00Z', prospects_processed: '2', drafts_created: '2', drafts_failed: '0', openai_cost_usd: '0.1000', errors: '', status: 'success' }] });
const logRun = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Log Run', parameters: { resource: 'sheet', operation: 'append', documentId: { __rl: true, mode: 'id', value: DRAFTER_LOG_ID }, sheetName: { __rl: true, mode: 'name', value: DRAFTER_LOG_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { useAppend: true, handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [2440, 700] }, output: [{ ok: true }] });

export default workflow('grp-outreach-drafter', 'GRP - Outreach Drafter (Daily)')
  .add(trig)
  .to(dayRouter)
  .to(skipIf
    .onTrue(shapeSkipRow.to(logSkipped))
    .onFalse(readBrand.to(readTemplates).to(loadContext).to(readPipeline).to(filterSort).to(noNewIf
      .onTrue(shapeRunLog)
      .onFalse(loop
        .onDone(shapeRunLog)
        .onEachBatch(
          scrapeWeb
            .to(extractCtx)
            .to(draftEmail)
            .to(parseDraft)
            .to(shapeDraftDoc)
            .to(saveDraft)
            .to(shapeStatusUpdate)
            .to(updateStatus)
            .to(nextBatch(loop))
        )
      )
    ))
  )
  .add(shapeRunLog)
  .to(logRun);
