// Canonical source for n8n workflow: GRP - Prospect Harvester (Daily)
// Workflow ID: YGMtaRA9YvYqBC0B
//
// 2026-04-27 v5 — GOOGLE PLACES API (NEW) — single Text Search call returns websites
//
//   Switched from legacy Places API to Places API (New). One request returns name,
//   address, websiteUri, phone, place_id directly via FieldMask — no Place Details
//   fan-out needed. Cost drops to ~$0.10/day, architecture loses three nodes.
//
// SOURCE: Google Maps Places API (NEW)
//   - Endpoint:    POST https://places.googleapis.com/v1/places:searchText
//   - Auth:        X-Goog-Api-Key header (httpHeaderAuth credential)
//   - FieldMask:   places.id, places.displayName, places.formattedAddress,
//                  places.websiteUri, places.nationalPhoneNumber
//   - Body:        { "textQuery": "digital marketing agency <city>", "pageSize": 20 }
//   - Pagination:  POST { "pageToken": "..." } in body. n8n HTTP node pagination
//                  injects pageToken as a body param on requests 2+, halts when
//                  nextPageToken is absent. Max 3 pages × 20 = 60 results/day.
//
// CREDENTIAL: "Google Maps API" — n8n credential type httpHeaderAuth, header name
//   X-Goog-Api-Key, value = the API key from Google Cloud Console (Sapienbotics
//   project; Places API New must be enabled). Saurabh switches this credential's
//   type from httpQueryAuth (legacy v4) to httpHeaderAuth (v5).
//
// CITY ROTATION: 18 cities cycled by (dayOfYear % 18). Per spec.
//
// ARCHITECTURE (v5 — three nodes shorter than v4):
//   trig → cityRouter → skipIf
//     ├ onTrue (Sunday): shapeSkipRow → logSkipped
//     └ onFalse:
//         placesSearch (POST, paginated body) → parsePlaces → hasProspects?
//           ├ onTrue (no places with website): shapeRunLog → logRun
//           └ onFalse: readExisting → dedup → hasNewIf?
//               ├ onTrue (all dupes): shapeRunLog → logRun
//               └ onFalse: scoreLoop (per prospect: scrape → AI score+founder)
//                   onDone: sortRank → appendLoop
//                     onEachBatch: needsHunter? → (true: Hunter→shape→appendA)
//                                              / (false: shape→appendB)
//                     onDone: shapeRunLog → logRun
//
// To deploy:
//   1. update_workflow(workflowId='YGMtaRA9YvYqBC0B', code=<this file>)
//   2. publish_workflow(workflowId='YGMtaRA9YvYqBC0B')
//
// SDK gotcha (kept for posterity): the parser blocks Array.prototype.join() at
// module scope. All multi-line jsCode is a single double-quoted string with \n.

import { workflow, node, trigger, ifElse, splitInBatches, nextBatch, newCredential, expr } from '@n8n/workflow-sdk';

const PROSPECT_PIPELINE_ID = '1sOtDT4OXPu2pVcmLepDyippa0vMXezr9EIsXMcP8iP0';
const PROSPECT_PIPELINE_TAB = 'Prospect-Pipeline';
const HARVESTER_LOG_ID = '1pBPuJQK4WYvSepqvzHGAN3CBsXxzRvCkw5R5ZFsyHYs';
const HARVESTER_LOG_TAB = 'Harvester-Log';

const trig = trigger({ type: 'n8n-nodes-base.scheduleTrigger', version: 1.3, config: { name: 'Daily 6AM IST', parameters: { rule: { interval: [{ field: 'cronExpression', expression: '0 30 0 * * *' }] } }, position: [240, 300] }, output: [{ 'Day of week': 'Monday', timestamp: '2026-04-27T00:30:00.000Z' }] });

const cityRouter = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'City Router', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "const cities = [\n  { city: 'New York',       country: 'United States' },\n  { city: 'Los Angeles',    country: 'United States' },\n  { city: 'Chicago',        country: 'United States' },\n  { city: 'London',         country: 'United Kingdom' },\n  { city: 'Toronto',        country: 'Canada' },\n  { city: 'Sydney',         country: 'Australia' },\n  { city: 'Dubai',          country: 'United Arab Emirates' },\n  { city: 'Singapore',      country: 'Singapore' },\n  { city: 'San Francisco',  country: 'United States' },\n  { city: 'Austin',         country: 'United States' },\n  { city: 'Miami',          country: 'United States' },\n  { city: 'Seattle',        country: 'United States' },\n  { city: 'Manchester',     country: 'United Kingdom' },\n  { city: 'Melbourne',      country: 'Australia' },\n  { city: 'Vancouver',      country: 'Canada' },\n  { city: 'Berlin',         country: 'Germany' },\n  { city: 'Amsterdam',      country: 'Netherlands' },\n  { city: 'Dublin',         country: 'Ireland' }\n];\nconst dayMap = { Sunday: 0, Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6 };\nconst item = $input.first();\nconst dowStr = (item && item.json) ? item.json['Day of week'] : null;\nlet day;\nif (dowStr && dayMap[dowStr] !== undefined) { day = dayMap[dowStr]; }\nelse { const now = new Date(); const ist = new Date(now.getTime() + (5.5 * 60 * 60 * 1000)); day = ist.getUTCDay(); }\nconst is_sunday = day === 0;\nconst istNow = new Date(new Date().getTime() + (5.5 * 60 * 60 * 1000));\nconst yearStart = new Date(istNow.getUTCFullYear(), 0, 1);\nconst dayOfYear = Math.floor((istNow.getTime() - yearStart.getTime()) / 86400000) + 1;\nconst idx = dayOfYear % cities.length;\nconst pick = cities[idx];\nconst places_query = 'digital marketing agency ' + pick.city;\nreturn [{ json: { day: day, is_sunday: is_sunday, run_date: istNow.toISOString().slice(0, 10), city: pick.city, country: pick.country, city_index: idx, places_query: places_query } }];" }, position: [440, 300] }, output: [{ day: 1, is_sunday: false, run_date: '2026-04-27', city: 'Austin', country: 'United States', city_index: 9, places_query: 'digital marketing agency Austin' }] });

const skipIf = ifElse({ version: 2.3, config: { name: 'Skip Sunday?', parameters: { conditions: { combinator: 'and', options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 }, conditions: [{ leftValue: expr('{{ $json.is_sunday }}'), rightValue: true, operator: { type: 'boolean', operation: 'true' } }] } }, position: [640, 300] } });

const shapeSkipRow = node({ type: 'n8n-nodes-base.set', version: 3.4, config: { name: 'Shape Skip Row', parameters: { mode: 'manual', assignments: { assignments: [{ id: 's1', name: 'date', value: expr('{{ $now.toISO() }}'), type: 'string' }, { id: 's2', name: 'source', value: 'google_places', type: 'string' }, { id: 's3', name: 'prospects_attempted', value: '0', type: 'string' }, { id: 's4', name: 'prospects_added', value: '0', type: 'string' }, { id: 's5', name: 'duplicates_skipped', value: '0', type: 'string' }, { id: 's6', name: 'apollo_credits_used', value: '0', type: 'string' }, { id: 's7', name: 'hunter_credits_used', value: '0', type: 'string' }, { id: 's8', name: 'openai_cost_usd', value: '0', type: 'string' }, { id: 's9', name: 'errors', value: '', type: 'string' }, { id: 's10', name: 'status', value: 'skipped_sunday', type: 'string' }] }, includeOtherFields: false }, position: [840, 100] }, output: [{ status: 'skipped_sunday' }] });

const logSkipped = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Log Skipped Run', parameters: { resource: 'sheet', operation: 'append', documentId: { __rl: true, mode: 'id', value: HARVESTER_LOG_ID }, sheetName: { __rl: true, mode: 'name', value: HARVESTER_LOG_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { useAppend: true, handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [1040, 100] }, output: [{ ok: true }] });

// Places API (New) — POST /v1/places:searchText
//   Headers:  X-Goog-FieldMask (set inline) + X-Goog-Api-Key (from credential)
//   Body:     { textQuery, pageSize: 20 } — keypair mode, pagination injects pageToken
//   Response: { places: [...], nextPageToken?: string }
const placesSearch = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Places Text Search', parameters: { method: 'POST', url: 'https://places.googleapis.com/v1/places:searchText', authentication: 'genericCredentialType', genericAuthType: 'httpHeaderAuth', sendHeaders: true, specifyHeaders: 'keypair', headerParameters: { parameters: [{ name: 'X-Goog-FieldMask', value: 'places.id,places.displayName,places.formattedAddress,places.websiteUri,places.nationalPhoneNumber' }] }, sendBody: true, contentType: 'json', specifyBody: 'keypair', bodyParameters: { parameters: [{ name: 'textQuery', value: expr('{{ $json.places_query }}') }, { name: 'pageSize', value: expr('{{ 20 }}') }] }, options: { response: { response: { responseFormat: 'json', neverError: true } }, timeout: 30000, pagination: { pagination: { paginationMode: 'updateAParameterInEachRequest', parameters: { parameters: [{ type: 'body', name: 'pageToken', value: '={{ $response.body.nextPageToken }}' }] }, paginationCompleteWhen: 'other', completeExpression: '={{ !$response.body.nextPageToken }}', limitPagesFetched: true, maxRequests: 3, requestInterval: 1500 } } } }, credentials: { httpHeaderAuth: newCredential('Google Maps API') }, alwaysOutputData: true, position: [840, 350] }, output: [{ places: [{ id: 'ChIJexample', displayName: { text: 'Acme Digital' }, formattedAddress: '123 Main St, Austin, TX, USA', websiteUri: 'https://acme.com', nationalPhoneNumber: '(512) 555-0100' }] }] });

// Single parser — replaces v4's parsePlaceIds + parseDetails. Maps Places API New
// shape to our prospect record, drops places without websiteUri, dedupes by place_id.
const parsePlaces = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Parse Places', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "function normDomain(url){ return String(url || '').trim().toLowerCase().replace(/^https?:\\/\\//, '').replace(/^www\\./, '').split('/')[0].split('?')[0]; }\nconst cityMeta = (($('City Router').first() || {}).json) || {};\nconst items = $input.all();\nconst out = [];\nconst seen = new Set();\nlet pages = 0;\nlet placesError = '';\nlet rawTotal = 0;\nfor (const it of items) {\n  pages++;\n  const j = (it && it.json) ? it.json : {};\n  if (j && j.error) {\n    const e = j.error;\n    placesError = String((e.status || e.message || 'places_error')).slice(0, 200);\n    continue;\n  }\n  const places = Array.isArray(j.places) ? j.places : [];\n  rawTotal += places.length;\n  for (const p of places) {\n    const place_id = String((p && p.id) || '').trim();\n    if (!place_id || seen.has(place_id)) continue;\n    seen.add(place_id);\n    const company = String((p && p.displayName && p.displayName.text) || '').trim();\n    const formatted_address = String((p && p.formattedAddress) || '').trim();\n    const websiteRaw = String((p && p.websiteUri) || '').trim();\n    if (!websiteRaw) continue;\n    const cleanWebsite = websiteRaw.replace(/\\/$/, '');\n    const domain = normDomain(cleanWebsite);\n    if (!domain) continue;\n    const phone = String((p && p.nationalPhoneNumber) || '').trim();\n    out.push({ company: company || domain, source: 'google_places', founder_name: '', email: '', linkedin_url: '', website: cleanWebsite, country: cityMeta.country || '', city: cityMeta.city || '', employee_count: '', services: '', title: '', domain: domain, place_id: place_id, formatted_address: formatted_address, phone: phone });\n  }\n}\nif (out.length === 0) {\n  return [{ json: { _no_prospects: true, places_total: rawTotal, places_pages: pages, places_error: placesError || 'no_results_with_website' } }];\n}\nreturn out.map(p => ({ json: { ...p, _meta_places_total: out.length, _meta_places_pages: pages, _meta_places_raw: rawTotal, _meta_places_error: placesError } }));" }, position: [1040, 350] }, output: [{ company: 'Acme Digital', source: 'google_places', website: 'https://acme.com', country: 'United States', city: 'Austin', domain: 'acme.com', place_id: 'ChIJexample', formatted_address: '123 Main St, Austin, TX, USA', phone: '(512) 555-0100', _meta_places_total: 1, _meta_places_pages: 1, _meta_places_raw: 1, _meta_places_error: '' }] });

const hasProspects = ifElse({ version: 2.3, config: { name: 'Have Prospects?', parameters: { conditions: { combinator: 'and', options: { caseSensitive: true, leftValue: '', typeValidation: 'loose', version: 2 }, conditions: [{ leftValue: expr('{{ $json._no_prospects }}'), rightValue: true, operator: { type: 'boolean', operation: 'true' } }] }, looseTypeValidation: true }, position: [1240, 350] } });

const readExisting = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Read Existing Pipeline', parameters: { resource: 'sheet', operation: 'read', documentId: { __rl: true, mode: 'id', value: PROSPECT_PIPELINE_ID }, sheetName: { __rl: true, mode: 'name', value: PROSPECT_PIPELINE_TAB }, options: { returnAllMatches: 'returnAllMatches', dataLocationOnSheet: { values: { rangeDefinition: 'detectAutomatically', readRowsUntil: 'lastRowInSheet' } } } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, alwaysOutputData: true, executeOnce: true, position: [1440, 400] }, output: [{ company: 'OldCo', website: 'https://old-co.com', status: 'drafted' }] });

const dedup = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Dedup Prospects', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "function normW(w){ if (!w) return ''; return String(w).trim().toLowerCase().replace(/^https?:\\/\\//, '').replace(/^www\\./, '').replace(/\\/$/, '').split('/')[0]; }\nconst existing = $input.all();\nconst known = new Set();\nfor (const it of existing) {\n  const j = (it && it.json) ? it.json : {};\n  if (j.website) known.add(normW(j.website));\n  if (j.domain)  known.add(String(j.domain).toLowerCase());\n}\nconst fresh = $('Parse Places').all();\nconst out = [];\nlet attempted = 0;\nlet dupes = 0;\nlet placesError = '';\nlet placesTotal = 0;\nfor (const it of fresh) {\n  const j = (it && it.json) ? it.json : {};\n  if (j._no_prospects) { placesTotal = j.places_total || 0; placesError = j.places_error || ''; continue; }\n  placesTotal = j._meta_places_total || placesTotal;\n  placesError = j._meta_places_error || placesError;\n  attempted++;\n  const w = normW(j.website);\n  if (!w || known.has(w) || known.has(j.domain)) { dupes++; continue; }\n  known.add(w);\n  out.push({ company: j.company, source: j.source, founder_name: j.founder_name, email: '', linkedin_url: j.linkedin_url, website: j.website, country: j.country, city: j.city, employee_count: j.employee_count, services: j.services, title: j.title, domain: j.domain, place_id: j.place_id, formatted_address: j.formatted_address, phone: j.phone });\n}\nconst meta = { _meta_attempted: attempted, _meta_dupes: dupes, _meta_places_total: placesTotal, _meta_places_error: placesError };\nif (out.length === 0) return [{ json: { ...meta, _no_new: true } }];\nreturn out.map(p => ({ json: { ...p, ...meta } }));" }, position: [1640, 400] }, output: [{ company: 'Acme Digital', domain: 'acme.com', website: 'https://acme.com', _meta_attempted: 1, _meta_dupes: 0, _meta_places_total: 1, _meta_places_error: '' }] });

const hasNewIf = ifElse({ version: 2.3, config: { name: 'Has New Prospects?', parameters: { conditions: { combinator: 'and', options: { caseSensitive: true, leftValue: '', typeValidation: 'loose', version: 2 }, conditions: [{ leftValue: expr('{{ $json._no_new }}'), rightValue: true, operator: { type: 'boolean', operation: 'true' } }] }, looseTypeValidation: true }, position: [1840, 400] } });

const scoreLoop = splitInBatches({ version: 3, config: { name: 'Score Loop', parameters: { batchSize: 1 }, position: [2040, 450] } });

// Scrape Website — best-effort homepage fetch. Many agency sites are slow, geo-walled,
// or behind Cloudflare; we don't want any of that to halt the whole workflow.
//   timeout: 30000             — 30s upper bound per host
//   neverError: true           — catches HTTP-level errors (4xx/5xx, parse failures)
//   onError: continueRegularOutput — catches transport-level errors (DNS, ECONNREFUSED)
//   alwaysOutputData: true     — emits an item even when both above fire
// Downstream Score Prompt uses `($json.data || "").slice(0, 4000)` which coalesces
// missing/failed scrape to an empty excerpt; the AI's system prompt says to be
// conservative when info is missing, so the OpenAI call still produces a usable
// fit_score from Places-only data (company, address, country).
const scrapeWebsite = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Scrape Website', parameters: { method: 'GET', url: expr('{{ $json.website }}'), sendHeaders: true, specifyHeaders: 'keypair', headerParameters: { parameters: [{ name: 'User-Agent', value: 'Mozilla/5.0 (compatible; GoReportPilot-Harvester/1.0)' }, { name: 'Accept', value: 'text/html,application/xhtml+xml' }] }, options: { response: { response: { responseFormat: 'text', neverError: true } }, timeout: 30000, redirect: { redirect: { followRedirects: true, maxRedirects: 5 } } } }, alwaysOutputData: true, onError: 'continueRegularOutput', position: [2240, 450] }, output: [{ data: '<html><h1>Acme Digital</h1><p>Founded by Jane Doe, CEO.</p></html>' }] });

const scoreProspect = node({ type: '@n8n/n8n-nodes-langchain.openAi', version: 2.1, config: { name: 'Score Prospect', parameters: { resource: 'text', operation: 'response', modelId: { __rl: true, mode: 'id', value: 'gpt-4o-mini' }, responses: { values: [{ type: 'text', role: 'system', content: "You analyze a digital marketing agency's website to (a) score ICP fit and (b) extract founder/CEO/owner name from the page text.\n\nGoReportPilot is a B2B SaaS that automates agency client reporting (GA4 + Meta Ads + Google Ads + Search Console).\n\nOutput ONLY JSON: {\"fit_score\": integer 1-10, \"founder_name\": \"string or empty\", \"founder_title\": \"string or empty\", \"signal_notes\": \"1-2 sentence rationale\"}\n\nFit scoring:\n- Higher (7-10): visible client logos, PPC/Meta/GA4 reporting in services, country US/UK/CA/AU/SG/AE/DE/NL/IE, agency 2-30 employees, marketing tech stack mentioned.\n- Lower (1-4): India location, in-house team, generic dev shop, no client work shown.\n- Be conservative: most should score 4-7.\n\nFounder extraction:\n- Pull the founder/CEO/owner/managing-director name if it appears on the homepage (about, team, footer, by-line, leadership section).\n- If no clear name, leave founder_name and founder_title as empty strings.\n- Do NOT invent. Empty is correct when uncertain." }, { type: 'text', role: 'user', content: expr('Company: {{ $("Score Loop").item.json.company }}\nAddress: {{ $("Score Loop").item.json.formatted_address }}\nWebsite: {{ $("Score Loop").item.json.website }}\nCountry (from city rotation): {{ $("Score Loop").item.json.country }}\n\nWebsite excerpt:\n{{ ($json.data || "").slice(0, 4000) }}') }] }, simplify: true, options: { maxTokens: 350, temperature: 0.2, textFormat: { textOptions: [{ type: 'json_object' }] } } }, credentials: { openAiApi: newCredential('OpenAI') }, position: [2440, 450] }, output: [{ content: '{"fit_score": 8, "founder_name": "Jane Doe", "founder_title": "CEO", "signal_notes": "PPC + Meta agency, 12 employees, Austin."}' }] });

const parseScore = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Parse Score', parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const j = $input.item.json || {};\nlet raw = '';\nif (typeof j === 'string') raw = j;\nelse if (typeof j.content === 'string') raw = j.content;\nelse if (typeof j.text === 'string') raw = j.text;\nelse if (typeof j.output_text === 'string') raw = j.output_text;\nelse if (typeof j.output === 'string') raw = j.output;\nelse if (j.message && typeof j.message.content === 'string') raw = j.message.content;\nelse if (Array.isArray(j.output)) {\n  for (const o of j.output) { const cs = Array.isArray(o.content) ? o.content : (o.content ? [o.content] : []); for (const c of cs) { if (c && typeof c.text === 'string') raw += c.text; } }\n}\nif (!raw) raw = JSON.stringify(j);\nlet parsed = null;\ntry { parsed = JSON.parse(raw); } catch(e) { const m = raw.match(/\\{[\\s\\S]*\\}/); if (m) { try { parsed = JSON.parse(m[0]); } catch(_) {} } }\nif (!parsed || typeof parsed !== 'object') parsed = { fit_score: 5, founder_name: '', founder_title: '', signal_notes: 'parse_failed' };\nconst meta = $('Score Loop').item.json;\nconst founderFromAi = String(parsed.founder_name || '').trim();\nconst titleFromAi   = String(parsed.founder_title || '').trim();\nreturn { ...meta, fit_score: parseInt(parsed.fit_score, 10) || 5, founder_name: meta.founder_name || founderFromAi, title: meta.title || titleFromAi, signal_notes: String(parsed.signal_notes || '').slice(0, 250) };" }, position: [2640, 450] }, output: [{ company: 'Acme Digital', website: 'https://acme.com', founder_name: 'Jane Doe', title: 'CEO', fit_score: 8, signal_notes: 'PPC + Meta agency, 12 employees.' }] });

const sortRank = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Sort & Rank Prospects', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "const HUNTER_BUDGET = 2;\nconst items = $input.all();\nconst scored = [];\nfor (const it of items) {\n  const j = (it && it.json) ? it.json : {};\n  if (!j.company || !j.website) continue;\n  scored.push(j);\n}\nscored.sort((a, b) => (parseInt(b.fit_score, 10) || 0) - (parseInt(a.fit_score, 10) || 0));\nconst out = scored.map((p, i) => ({ ...p, _needs_hunter: i < HUNTER_BUDGET, _hunter_budget: HUNTER_BUDGET, _scored_total: scored.length }));\nif (out.length === 0) return [{ json: { _no_scored: true } }];\nreturn out.map(p => ({ json: p }));" }, position: [2840, 700] }, output: [{ company: 'Acme Digital', website: 'https://acme.com', fit_score: 8, _needs_hunter: true, _hunter_budget: 2, _scored_total: 1 }] });

const appendLoop = splitInBatches({ version: 3, config: { name: 'Append Loop', parameters: { batchSize: 1 }, position: [3040, 700] } });

const hasHunterFlag = ifElse({ version: 2.3, config: { name: 'Needs Hunter?', parameters: { conditions: { combinator: 'and', options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 }, conditions: [{ leftValue: expr('{{ $json._needs_hunter }}'), rightValue: true, operator: { type: 'boolean', operation: 'true' } }] } }, position: [3240, 700] } });

const hunterFetch = node({ type: 'n8n-nodes-base.httpRequest', version: 4.4, config: { name: 'Hunter Fetch', parameters: { method: 'GET', url: expr('https://api.hunter.io/v2/domain-search?domain={{ $json.domain }}&type=personal&limit=3'), authentication: 'genericCredentialType', genericAuthType: 'httpQueryAuth', options: { response: { response: { responseFormat: 'json', neverError: true } }, timeout: 30000 } }, credentials: { httpQueryAuth: newCredential('Hunter API') }, alwaysOutputData: true, position: [3440, 600] }, output: [{ data: { emails: [{ value: 'jane@acme.com', first_name: 'Jane', last_name: 'Doe', position: 'CEO', linkedin: 'https://linkedin.com/in/janedoe' }] } }] });

const parseHunter = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Parse Hunter', parameters: { mode: 'runOnceForEachItem', language: 'javaScript', jsCode: "const meta = $('Append Loop').item.json;\nconst r = $input.item.json || {};\nconst data = r.data || {};\nconst emails = Array.isArray(data.emails) ? data.emails : [];\nlet pick = emails.find(e => e.position && /found|owner|ceo|principal|managing/i.test(e.position)) || emails[0] || null;\nconst email = (pick && pick.value) || '';\nconst name = pick ? [pick.first_name, pick.last_name].filter(Boolean).join(' ') : '';\nconst linkedin = (pick && pick.linkedin) || '';\nreturn { ...meta, founder_name: meta.founder_name || name, email: email, linkedin_url: meta.linkedin_url || linkedin, _hunter_called: true };" }, position: [3640, 600] }, output: [{ company: 'Acme Digital', email: 'jane@acme.com', founder_name: 'Jane Doe', _hunter_called: true }] });

const shapeRowWithEmail = node({ type: 'n8n-nodes-base.set', version: 3.4, config: { name: 'Shape Row With Email', parameters: { mode: 'manual', assignments: { assignments: [{ id: 'pa1', name: 'company', value: expr('{{ $json.company }}'), type: 'string' }, { id: 'pa2', name: 'source', value: 'google_places', type: 'string' }, { id: 'pa3', name: 'founder_name', value: expr('{{ $json.founder_name }}'), type: 'string' }, { id: 'pa4', name: 'email', value: expr('{{ $json.email }}'), type: 'string' }, { id: 'pa5', name: 'linkedin_url', value: expr('{{ $json.linkedin_url }}'), type: 'string' }, { id: 'pa6', name: 'website', value: expr('{{ $json.website }}'), type: 'string' }, { id: 'pa7', name: 'country', value: expr('{{ $json.country }}'), type: 'string' }, { id: 'pa8', name: 'employee_count', value: expr('{{ $json.employee_count }}'), type: 'string' }, { id: 'pa9', name: 'services', value: expr('{{ $json.services }}'), type: 'string' }, { id: 'pa10', name: 'fit_score', value: expr('{{ $json.fit_score }}'), type: 'string' }, { id: 'pa11', name: 'signal_notes', value: expr('{{ $json.signal_notes }}'), type: 'string' }, { id: 'pa12', name: 'status', value: expr('{{ $json.email && /@/.test($json.email) ? "new" : "new_no_email" }}'), type: 'string' }, { id: 'pa13', name: 'date_added', value: expr('{{ $now.toISO() }}'), type: 'string' }] }, includeOtherFields: false }, position: [3840, 600] }, output: [{ company: 'Acme Digital', source: 'google_places', founder_name: 'Jane Doe', email: 'jane@acme.com', website: 'https://acme.com', country: 'United States', fit_score: '8', status: 'new', date_added: '2026-04-27T00:30:00Z' }] });

const shapeRowNoEmail = node({ type: 'n8n-nodes-base.set', version: 3.4, config: { name: 'Shape Row No Email', parameters: { mode: 'manual', assignments: { assignments: [{ id: 'pb1', name: 'company', value: expr('{{ $json.company }}'), type: 'string' }, { id: 'pb2', name: 'source', value: 'google_places', type: 'string' }, { id: 'pb3', name: 'founder_name', value: expr('{{ $json.founder_name }}'), type: 'string' }, { id: 'pb4', name: 'email', value: '', type: 'string' }, { id: 'pb5', name: 'linkedin_url', value: expr('{{ $json.linkedin_url }}'), type: 'string' }, { id: 'pb6', name: 'website', value: expr('{{ $json.website }}'), type: 'string' }, { id: 'pb7', name: 'country', value: expr('{{ $json.country }}'), type: 'string' }, { id: 'pb8', name: 'employee_count', value: expr('{{ $json.employee_count }}'), type: 'string' }, { id: 'pb9', name: 'services', value: expr('{{ $json.services }}'), type: 'string' }, { id: 'pb10', name: 'fit_score', value: expr('{{ $json.fit_score }}'), type: 'string' }, { id: 'pb11', name: 'signal_notes', value: expr('{{ $json.signal_notes }}'), type: 'string' }, { id: 'pb12', name: 'status', value: 'new_no_email', type: 'string' }, { id: 'pb13', name: 'date_added', value: expr('{{ $now.toISO() }}'), type: 'string' }] }, includeOtherFields: false }, position: [3440, 800] }, output: [{ company: 'Acme Digital', source: 'google_places', email: '', status: 'new_no_email' }] });

const appendProspectA = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Append Prospect A', parameters: { resource: 'sheet', operation: 'append', documentId: { __rl: true, mode: 'id', value: PROSPECT_PIPELINE_ID }, sheetName: { __rl: true, mode: 'name', value: PROSPECT_PIPELINE_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { useAppend: true, handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [4040, 600] }, output: [{ ok: true }] });

const appendProspectB = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Append Prospect B', parameters: { resource: 'sheet', operation: 'append', documentId: { __rl: true, mode: 'id', value: PROSPECT_PIPELINE_ID }, sheetName: { __rl: true, mode: 'name', value: PROSPECT_PIPELINE_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { useAppend: true, handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [3640, 800] }, output: [{ ok: true }] });

const shapeRunLog = node({ type: 'n8n-nodes-base.code', version: 2, config: { name: 'Shape Run Log Row', parameters: { mode: 'runOnceForAllItems', language: 'javaScript', jsCode: "function safeFirstJson(name){ try { return ($(name).first() || {}).json || {}; } catch(e){ return {}; } }\nfunction safeAll(name){ try { return $(name).all() || []; } catch(e){ return []; } }\nconst dedupMeta = safeFirstJson('Dedup Prospects');\nconst placesMeta = safeFirstJson('Parse Places');\nconst cityMeta = safeFirstJson('City Router');\nconst sortAll = safeAll('Sort & Rank Prospects');\nconst noProspects = !!placesMeta._no_prospects;\nconst noNew = !!dedupMeta._no_new;\nconst attempted = dedupMeta._meta_attempted || (placesMeta._meta_places_total || 0);\nconst dupes = dedupMeta._meta_dupes || 0;\nconst placesError = dedupMeta._meta_places_error || placesMeta.places_error || placesMeta._meta_places_error || '';\nconst scoredItems = sortAll.filter(it => it && it.json && !it.json._no_scored);\nconst scoredCount = scoredItems.length;\nconst hunterUsed = scoredItems.filter(it => it.json._needs_hunter).length;\nconst added = scoredCount;\nconst openaiCost = (scoredCount * 0.0023).toFixed(4);\nlet status = 'success';\nif (placesError) status = 'places_error';\nelse if (noProspects) status = 'no_prospects_returned';\nelse if (noNew) status = 'all_duplicates';\nelse if (added === 0) status = 'no_new_added';\nconst errors = placesError ? ('places: ' + placesError) : '';\nreturn [{ json: { date: new Date().toISOString(), source: 'google_places (' + (cityMeta.city || 'unknown') + ')', prospects_attempted: String(attempted), prospects_added: String(added), duplicates_skipped: String(dupes), apollo_credits_used: '0', hunter_credits_used: String(hunterUsed), openai_cost_usd: openaiCost, errors: errors, status: status } }];" }, position: [3640, 1000] }, output: [{ date: '2026-04-27T00:30:00Z', source: 'google_places (Austin)', prospects_attempted: '5', prospects_added: '5', duplicates_skipped: '1', apollo_credits_used: '0', hunter_credits_used: '2', openai_cost_usd: '0.0115', errors: '', status: 'success' }] });

const logRun = node({ type: 'n8n-nodes-base.googleSheets', version: 4.7, config: { name: 'Log Run', parameters: { resource: 'sheet', operation: 'append', documentId: { __rl: true, mode: 'id', value: HARVESTER_LOG_ID }, sheetName: { __rl: true, mode: 'name', value: HARVESTER_LOG_TAB }, columns: { mappingMode: 'autoMapInputData', value: null, matchingColumns: [], schema: [], attemptToConvertTypes: false, convertFieldsToString: true }, options: { useAppend: true, handlingExtraData: 'ignoreIt' } }, credentials: { googleSheetsOAuth2Api: newCredential('Google Sheets') }, position: [3840, 1000] }, output: [{ ok: true }] });

export default workflow('grp-prospect-harvester', 'GRP - Prospect Harvester (Daily)')
  .add(trig)
  .to(cityRouter)
  .to(skipIf
    .onTrue(shapeSkipRow.to(logSkipped))
    .onFalse(placesSearch.to(parsePlaces).to(hasProspects
      .onTrue(shapeRunLog)
      .onFalse(readExisting.to(dedup).to(hasNewIf
        .onTrue(shapeRunLog)
        .onFalse(scoreLoop
          .onDone(sortRank.to(appendLoop
            .onDone(shapeRunLog)
            .onEachBatch(
              hasHunterFlag
                .onTrue(hunterFetch.to(parseHunter).to(shapeRowWithEmail).to(appendProspectA).to(nextBatch(appendLoop)))
                .onFalse(shapeRowNoEmail.to(appendProspectB).to(nextBatch(appendLoop)))
            )
          ))
          .onEachBatch(
            scrapeWebsite.to(scoreProspect).to(parseScore).to(nextBatch(scoreLoop))
          )
        )
      ))
    ))
  )
  .add(shapeRunLog)
  .to(logRun);
